app_id: "926c2066-8e1e-4108-89a2-f29b0082dc82"
app_secret: "vtc7P03ao~~rf4dj1Mf1-_x6Iu5isD0OI."
redirect: "http://localhost:8000/robots/callback"
scopes: "openid profile offline_access user.read calendars.read"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
