# Generated by Django 2.2.7 on 2020-08-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200813_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=500, verbose_name='العنوان:'),
            preserve_default=False,
        ),
    ]
