# Generated by Django 2.2.7 on 2020-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='who_is_me',
            field=models.TextField(default=1, max_length=500, verbose_name='العنوان:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=50, verbose_name='العنوان:'),
        ),
    ]
