# Generated by Django 3.1 on 2020-08-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200813_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='who_is_me',
            field=models.TextField(max_length=500, verbose_name='من انا:'),
        ),
    ]
